version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
  telegram_bot_api:
    build:
      context: ./telegram_bot_api
    restart: always
    depends_on:
      - rabbitmq
  web_api:
    build:
      context: ./web_api
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - 8000:8000
  model:
    build:
      context: ./model
    restart: always
    depends_on:
      - rabbitmq
      - telegram_bot_api
      - web_api
    volumes:
      - ./logs/:/usr/src/app/logs/
